a=int(input("first digit :"))
b=int(input("second digit :"))
c=int(input("third digit :"))
print("Addition",a+b)
print("c")
print("c","-",c)
print("c""c")
print("a+b =",c)
print("c =",a+b)
print("c =","a+b")
print("subtract",a-b)
print("multiplication",a*b)
print("Divison",a/b)
print("floor division(integer)",a//b)
print("power",a**b)
print("modulus",a%b)
print("BODMAS RULE",5+2*3-1+10/5)
print("gittest",3+3)